server:
  port: 8080
  servlet:
    context-path: /TopCV
    session:
      cookie:
        secure: true
        http-only: true
        same-site: strict

spring:
  application:
    name: TopCV
  datasource:
    url: "jdbc:postgresql://localhost:5432/TopCV"
    username: admin
    password: root
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000
      database: 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            protocols: TLSv1.2
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
        debug: false

jwt:
  signerKey: ${JWT_SIGNER_KEY}

app:
  name: ${APP_NAME:TopCV}
  url: ${APP_URL:http://localhost:8080/TopCV}
  security:
    otp:
      length: 6

firebase:
  config:
    project-id: ${FIREBASE_PROJECT_ID}
    storage-bucket: ${FIREBASE_STORAGE_BUCKET}
    client-email: ${FIREBASE_CLIENT_EMAIL}
    private-key: ${FIREBASE_PRIVATE_KEY}
    private-key-id: ${FIREBASE_PRIVATE_KEY_ID}

  storage:
    base-url: https://firebasestorage.googleapis.com/v0/b/topcv-job-portal-xxxxx.appspot.com/o
    public-folder: public
    private-folder: private